### ISSUE TITLE
Header problems

### ISSUE THREAD

**Issue by Kod25** [raho1501/Unofficial-Thesis-Template#1]
I have encountered an issue with the  template, the header.
The abstract page looks like this:

![Annotation](https://user-images.githubusercontent.com/32240854/74909626-fce25280-53b8-11ea-83c5-7df003c55566.png)

Then some sections dont have it:

![Annotation2](https://user-images.githubusercontent.com/32240854/74909799-5ba7cc00-53b9-11ea-9cd7-c37b0bfc9139.png)

But if that section is longer then 1 page it is there on the second page:

![Annotation3](https://user-images.githubusercontent.com/32240854/74909841-71b58c80-53b9-11ea-820b-95e0232308fe.png)

What did i break?

**Comment by raho1501** [comment]
changed so that abstract doesn't flow into header on that page, this was something i missed sine my titles are quite short. see commit 8fd108f899e6657419e3146d977729a39358af79 for solution.

the issue with inconsistent headers is that normal-pages and chapters-pages are treated differently, so you have to define your header text on line 44 and 96 in main.tex .

**Comment by Kod25** [comment]
Thank you!
